os: osx
language: objective-c
      
install:
    - curl -LO https://github.com/progrium/gh-release/releases/download/v2.2.0/gh-release_2.2.0_darwin_x86_64.tgz
script:
    - brew install gnu-sed --default-names

