os: osx
language: objective-c
branches:
  only:
    - master
install:
    - curl -L https://github.com/progrium/gh-release/releases/download/v2.2.0/gh-release_2.2.0_darwin_x86_64.tgz | tar -xz -C /usr/local/bin/
script:
    - brew install gnu-sed --default-names
    - mkdir -p release && tar -czvf release/sed-darwin-4.2.2.tgz  -C /usr/local/Cellar/gnu-sed/4.2.2/bin/ sed
    - gh-release create lalyos/gnused-osx-bin 4.2.2

